define({
    plaqueMessageSmall: {},
    buttonText: {},
    errorMessage: {
        fontFamily: 'oswald',
        fontSize: 30,
        align: 'center',
        fill: '#ffffff',
        padding: 10,
    },
    versionHelpText: {
        fontSize: 16,
        fontFamily: 'oswald',
        fill: "#ffffff"
    },
    errorButtonEnabled: {
        fontFamily: 'oswald',
        fontSize: 38,
        fill: "#ffffff",
        padding: 10,
    },
    errorButtonOver: {
        fontFamily: 'oswald',
        fontSize: 38,
        fill: "#ffffff",
        padding: 10,
    },
    errorButtonPressed: {
        fontFamily: 'oswald',
        fontSize: 30,
        fill: "#ffffff",
        padding: 10,
    },
    winningNumbersTitle: {
        fontFamily: 'oswald',
        fontWeight: 'bold',
        fontSize: 32,
        fill: 'fontColourLuckyNumberTitle'
    },
    playerNumbersTitle: {
        fontFamily: 'oswald',
        fontWeight: 'bold',
        fontSize: 32,
        fill: 'fontColourYourNumberTitle'
    },
    prizeValueNoWin: {
        fontFamily: 'oswald',
        fontSize: 30,
        fontWeight: 'bold',
        lineJoin: "round",
        miterLimit: 28,
        fill: 'fontColourCashValueNoWin'
    },
    prizeValueWin: {
        fontFamily: 'oswald',
        fontSize: 30,
        fontWeight: 'bold',
        lineJoin: "round",
        miterLimit: 28,
        fill: 'fontColourCashValueWin'
    },
    winUpToText: {
        fontFamily: 'oswald',
        fontSize: 30,
        fontWeight: 'normal',
        dropShadow: true,
        dropShadowBlur: 2,
        dropShadowAngle: 2,
        dropShadowDistance: 1,
        fill: [
            'white', '#fff3b0', '#ffac5a', '#ff8600'
        ],
        fillGradientStops: [
            0.2, 0.4, 0.5, 0.6
        ],
        lineJoin: "round",
        miterLimit: 28,
        padding: 41,
        stroke: "#ff8600",
        strokeThickness: 2
    },
    winUpToValue: {
        fontFamily: 'oswald',
        fontWeight: 'bold',
        fontSize: 50,
        dropShadow: true,
        dropShadowBlur: 2,
        dropShadowAngle: 2,
        dropShadowDistance: 1,
        fill: [
            'white', '#fff3b0', '#ffac5a', '#ff8600'
        ],
        fillGradientStops: [
            0.2, 0.4, 0.5, 0.6
        ],
        lineJoin: "round",
        miterLimit: 28,
        padding: 41,
        stroke: "#ff8600",
        strokeThickness: 2
    },
    winUpToTextShadow: {
        fontFamily: 'oswald',
        fontSize: 30,
        fontWeight: 'normal',
        dropShadow: true,
        dropShadowBlur: 2,
        dropShadowAngle: 2,
        dropShadowDistance: 1,
        fill: [
            '#d20064',
        ],
        lineJoin: "round",
        miterLimit: 28,
        padding: 41,
    },
    winUpToValueShadow: {
        fontFamily: 'oswald',
        fontSize: 50,
        fontWeight: 'bold',
        dropShadow: true,
        dropShadowBlur: 2,
        dropShadowAngle: 2,
        dropShadowDistance: 1,
        fill: [
            '#d20064',
        ],
        lineJoin: "round",
        miterLimit: 28,
        padding: 41,
    },
    bonusWin6: {
        fontFamily: 'oswald',
        fontSize: 92,
        fontWeight: 'bold',
        align: 'center',
        fill: 'bonusPayTableWinColour'
    },
    bonusNoWin6: {
        fontFamily: 'oswald',
        fontSize: 92,
        fontWeight: 'bold',
        align: 'center',
        fill: 'bonusPayTableNoWinColour'
    },
    bonusWin5: {
        fontFamily: 'oswald',
        fontSize: 82,
        fontWeight: 'bold',
        align: 'center',
        fill: 'bonusPayTableWinColour'
    },
    bonusNoWin5: {
        fontFamily: 'oswald',
        fontSize: 82,
        fontWeight: 'bold',
        align: 'center',
        fill: 'bonusPayTableNoWinColour'
    },
    bonusWin4: {
        fontFamily: 'oswald',
        fontSize: 72,
        fontWeight: 'bold',
        align: 'center',
        fill: 'bonusPayTableWinColour'
    },
    bonusNoWin4: {
        fontFamily: 'oswald',
        fontSize: 72,
        fontWeight: 'bold',
        align: 'center',
        fill: 'bonusPayTableNoWinColour'
    },
    bonusWin3: {
        fontFamily: 'oswald',
        fontSize: 62,
        fontWeight: 'bold',
        align: 'center',
        fill: 'bonusPayTableWinColour'
    },
    bonusNoWin3: {
        fontFamily: 'oswald',
        fontSize: 62,
        fontWeight: 'bold',
        align: 'center',
        fill: 'bonusPayTableNoWinColour'
    },
    bonusWin: {
        fontFamily: 'oswald',
        fontSize: 62,
        fontWeight: 'bold',
        align: 'center',
        lineJoin: "round",
        miterLimit: 28,
        fill: 'bonusPayTableWinColour'
    },
    bonusNoWin: {
        fontFamily: 'oswald',
        fontSize: 62,
        fontWeight: 'bold',
        align: 'center',
        lineJoin: "round",
        miterLimit: 28,
        fill: 'bonusPayTableNoWinColour'
    },
    losePlaqueBody: {
        fontFamily: 'oswald',
        fontSize: 50,
        fontWeight: 'bold',
        align: 'center',
        fill: '#8FFFFF',
        padding: 10
    },
    winPlaqueBody: {
        fontFamily: 'oswald',
        fontSize: 60,
        fontWeight: 'bold',
        dropShadow: true,
        dropShadowBlur: 2,
        dropShadowAngle: 2,
        dropShadowDistance: 1,
        fill: [
            "white",
            "#d1dfff",
            "#d1e4ff"
        ],
        fillGradientStops: [
            0.3,
            0.6
        ],
        lineJoin: "round",
        miterLimit: 28,
        padding: 41,
        stroke: "#092f6c",
        strokeThickness: 5,
        align: 'center'
    },
    winPlaqueValue: {
        fontFamily: 'oswald',
        fontSize: 120,
        fontWeight: 'bold',
        dropShadow: true,
        dropShadowBlur: 2,
        dropShadowAngle: 2,
        dropShadowDistance: 1,
        fill: [
            "white",
            "#d1dfff",
            "#d1e4ff"
        ],
        fillGradientStops: [
            0.3,
            0.6
        ],
        lineJoin: "round",
        miterLimit: 28,
        padding: 41,
        stroke: "#092f6c",
        strokeThickness: 5
    },
    buyButtonEnabled: {
        fontFamily: 'oswald',
        fontSize: 38,
        fontWeight: 'bold',
        fill: "#fffdf0",
        padding: 10,
        dropShadow: true,
        dropShadowBlur: 2,
        dropShadowAngle: 2,
        dropShadowDistance: 1,
    },
    buyButtonDisabled: {
        fontFamily: 'oswald',
        fontSize: 38,
        fontWeight: 'bold',
        fill: "#fffdf0",
        padding: 10,
        dropShadow: true,
        dropShadowBlur: 2,
        dropShadowAngle: 2,
        dropShadowDistance: 1,
    },
    buyButtonOver: {
        fontFamily: 'oswald',
        fontSize: 38,
        fontWeight: 'bold',
        fill: "#fffdf0",
        padding: 10,
        dropShadow: true,
        dropShadowBlur: 2,
        dropShadowAngle: 2,
        dropShadowDistance: 1,
    },
    buyButtonPressed: {
        fontFamily: 'oswald',
        fontSize: 30,
        fontWeight: 'bold',
        fill: "#fffdf0",
        padding: 10,
        dropShadow: true,
        dropShadowBlur: 2,
        dropShadowAngle: 2,
        dropShadowDistance: 1,
    },
    tutorialOKButtonEnabled: {
        fontFamily: 'oswald',
        fontSize: 38,
        fontWeight: 'bold',
        fill: "#fffdf0",
        padding: 10,
        dropShadow: true,
        dropShadowBlur: 2,
        dropShadowAngle: 2,
        dropShadowDistance: 1,
    },
    tutorialOKButtonOver: {
        fontFamily: 'oswald',
        fontSize: 38,
        fontWeight: 'bold',
        fill: "#fffdf0",
        padding: 10,
        dropShadow: true,
        dropShadowBlur: 2,
        dropShadowAngle: 2,
        dropShadowDistance: 1,
    },
    tutorialOKButtonPressed: {
        fontFamily: 'oswald',
        fontSize: 30,
        fontWeight: 'bold',
        fill: "#fffdf0",
        padding: 10,
        dropShadow: true,
        dropShadowBlur: 2,
        dropShadowAngle: 2,
        dropShadowDistance: 1,
    },
    mainButtonEnabled: {
        fontFamily: 'oswald',
        fontSize: 38,
        fontWeight: 'bold',
        fill: "#fffdf0",
        padding: 10,
        dropShadow: true,
        dropShadowBlur: 2,
        dropShadowAngle: 2,
        dropShadowDistance: 1,
    },
    mainButtonDisabled: {
        fontFamily: 'oswald',
        fontSize: 38,
        fontWeight: 'bold',
        fill: "#fffdf0",
        padding: 10,
        dropShadow: true,
        dropShadowBlur: 2,
        dropShadowAngle: 2,
        dropShadowDistance: 1,
    },
    mainButtonOver: {
        fontFamily: 'oswald',
        fontSize: 38,
        fontWeight: 'bold',
        fill: "#fffdf0",
        padding: 10,
        dropShadow: true,
        dropShadowBlur: 2,
        dropShadowAngle: 2,
        dropShadowDistance: 1,
    },
    mainButtonPressed: {
        fontFamily: 'oswald',
        fontSize: 30,
        fontWeight: 'bold',
        fill: "#fffdf0",
        padding: 10,
        dropShadow: true,
        dropShadowBlur: 2,
        dropShadowAngle: 2,
        dropShadowDistance: 1,
    },
    winUpTo: {
        fontFamily: 'oswald',
        fontSize: 40,
        fontWeight: 'bold',
        fill: 'fontColourWinUpToTitle'
    },
    howToPlayTitle: {
        fill: '#ffffff',
        fontFamily: 'oswald',
        fontWeight: 'bold',
        fontSize: 30,
        padding: 10,
    },
    howToPlayInfoText: {
        fontFamily: 'oswald',
        fontSize: 30,
        fill: '#ffffff',
        padding: 10,
    },
    HowToPlayTitle2: {
        fontFamily: 'oswald',
        fontSize: 50,
        fontWeight: 'bold',
        dropShadow: true,
        dropShadowBlur: 2,
        dropShadowAngle: 2,
        dropShadowDistance: 1,
        fill: [
            'white', '#fff3b0', '#ffac5a', '#ff8600'
        ],
        fillGradientStops: [
            0.2, 0.4, 0.5, 0.6
        ],
        lineJoin: "round",
        miterLimit: 28,
        padding: 41,
        stroke: "#ff8600",
        strokeThickness: 2
    },
    pickPointAmount: {
        fontFamily: 'oswald',
        fontSize: 20,
        fill: '#b5c8e0',
        stroke: '#240058',
        strokeThickness: 4,
        padding: 10,
        lineJoin: "round",
        miterLimit: 28,
    },
    pickPointAmountWinMultiplier: {
        fontFamily: 'oswald',
        fontSize: 20,
        fill: '#fada09',
        stroke: '#a80149',
        strokeThickness: 4,
        padding: 10,
        lineJoin: "round",
        miterLimit: 28,
    },
    pickPointAmountWin: {
        fontFamily: 'oswald',
        fontSize: 20,
        fill: '#fada09',
        stroke: '#a80149',
        strokeThickness: 4,
        padding: 10,
        lineJoin: "round",
        miterLimit: 28,
    },
    ticketSelectCostValue: {
        fontFamily: 'oswald',
        fontSize: 35,
        fill: '#FFFFFF',
        stroke: '#4800be',
        strokeThickness: 2,
        padding: 10,
        lineJoin: "round",
        miterLimit: 28,
        fontWeight: 'bold',
    },
    ticketSelectCostHeader: {
        fontFamily: 'oswald',
        fontSize: 25,
        fill: '#FFFFFF',
        padding: 10,
        stroke: '#240058',
        strokeThickness: 4,
        dropShadow: true,
        dropShadowBlur: 2,
        dropShadowAngle: 2,
        dropShadowDistance: 1,
        lineJoin: "round",
        miterLimit: 28,
    },
    totalTicketSelectCostHeader: {
        fontFamily: 'oswald',
        fontSize: 25,
        fill: '#ffffff',
        padding: 10,
        stroke: '#000000',
        strokeThickness: 4,
        lineJoin: "round",
        miterLimit: 28,
        fontWeight: 'bold',
    },
    totalTicketSelectCostValue: {
        fontFamily: 'oswald',
        fontSize: 32,
        fill: '#ffffff',
        padding: 10,
        stroke: '#000000',
        strokeThickness: 4,
        lineJoin: "round",
        miterLimit: 28,
        fontWeight: 'bold',
    },
    bonusRowHeader: {
        fontFamily: 'oswald',
        fontSize: 32,
        fill: '#ffffff',
        padding: 10,
        stroke: '#000000',
        strokeThickness: 4,
        lineJoin: "round",
        miterLimit: 28,
        fontWeight: 'bold',
    },
    wheelGameSegment: {
        fontFamily: 'oswald',
        fontSize: 40,
        fill: '#ffffff',
        padding: 10,
        stroke: '#000000',
        strokeThickness: 4,
        lineJoin: "round",
        miterLimit: 28,
        fontWeight: 'bold',
    },
    wheelGameSegmentWin: {
        fontFamily: 'oswald',
        fontSize: 40,
        fill: '#fada09',
        stroke: '#a80149',
        strokeThickness: 4,
        lineJoin: "round",
        miterLimit: 28,
        fontWeight: 'bold',
    },
    transitionTitle: {
        fontFamily: 'oswald',
        fontSize: 80,
        fontWeight: 'bold',
        dropShadow: true,
        dropShadowBlur: 2,
        dropShadowAngle: 2,
        dropShadowDistance: 1,
        fill: [
            'white', '#fff3b0', '#ffac5a', '#ff8600'
        ],
        fillGradientStops: [
            0.2, 0.4, 0.5, 0.6
        ],
        lineJoin: "round",
        miterLimit: 28,
        padding: 41,
        stroke: "#ff8600",
        strokeThickness: 2
    },
    infoText: {
        fontFamily: 'oswald',
        fontSize: 21,
        fill: '#FFFFFF',
        padding: 10,
        lineJoin: "round",
        miterLimit: 28,
        align: 'center',
        letterSpacing: 1,
        lineHeight: 30
    },
    spinButton: {
        fontFamily: 'oswald',
        fontSize: 50,
        fontWeight: 'bold',
        fill: '#FFFFFF',
        padding: 10,
        lineJoin: "round",
        miterLimit: 28,
        align: 'center',
        letterSpacing: 1,
        lineHeight: 30,
        dropShadow: true,
        dropShadowBlur: 2,
        dropShadowAngle: 2,
        dropShadowDistance: 1,
    },
});